//
//  ContentView.swift
//  task32
//
//  Created by Student on 4/23/26.
//

import SwiftUI

struct ContentView: View {
    var body: some View {
        VStack {
            Image(systemName: "eraser")
                .imageScale(.large)
                .foregroundStyle(.tint)
            Text("iabgseweuhBFAWUYFGWeuyfweyFHWEYFVAWEGFAEUGVWYEVGFWgwgyybaghjvsuygbgvyrdasfgvbarg asfvaifhmwq8ecngwa8e gtvw8efhaweuftgewaygnerhyfgwe78frhmrgcruHR iyrygmHFYUAWGFHAWF HGAEGYAERURHGMAEROUIGHAEURIGFHAERWUGFHAERUGHAEYUGiabgseweuhBFAWUYFGWeuyfweyFHWEYFVAWEGFAEUGVWYEVGFWgwgyybaghjvsuygbgvyrdasfgvbarg asfvaifhmwq8ecngwa8e gtvw8efhaweuftgewaygnerhyfgwe78frhmrgcruHR iyrygmHFYUAWGFHAWF HGAEGYAERURHGMAEROUIGHAEURIGFHAERWUGFHAERUGHAEYUGiabgseweuhBFAWUYFGWeuyfweyFHWEYFVAWEGFAEUGVWYEVGFWgwgyybaghjvsuygbgvyrdasfgvbarg asfvaifhmwq8ecngwa8e gtvw8efhaweuftgewaygnerhyfgwe78frhmrgcruHR iyrygmHFYUAWGFHAWF HGAEGYAERURHGMAEROUIGHAEURIGFHAERWUGFHAERUGHAEYUGiabgseweuhBFAWUYFGWeuyfweyFHWEYFVAWEGFAEUGVWYEVGFWgwgyybaghjvsuygbgvyrdasfgvbarg asfvaifhmwq8ecngwa8e gtvw8efhaweuftgewaygnerhyfgwe78frhmrgcruHR iyrygmHFYUAWGFHAWF HGAEGYAERURHGMAEROUIGHAEURIGFHAERWUGFHAERUGHAEYUGiabgseweuhBFAWUYFGWeuyfweyFHWEYFVAWEGFAEUGVWYEVGFWgwgyybaghjvsuygbgvyrdasfgvbarg asfvaifhmwq8ecngwa8e gtvw8efhaweuftgewaygnerhyfgwe78frhmrgcruHR iyrygmHFYUAWGFHAWF HGAEGYAERURHGMAEROUIGHAEURIGFHAERWUGFHAERUGHAEYUGiabgseweuhBFAWUYFGWeuyfweyFHWEYFVAWEGFAEUGVWYEVGFWgwgyybaghjvsuygbgvyrdasfgvbarg asfvaifhmwq8ecngwa8e gtvw8efhaweuftgewaygnerhyfgwe78frhmrgcruHR iyrygmHFYUAWGFHAWF HGAEGYAERURHGMAEROUIGHAEURIGFHAERWUGFHAERUGHAEYUGiabgseweuhBFAWUYFGWeuyfweyFHWEYFVAWEGFAEUGVWYEVGFWgwgyybaghjvsuygbgvyrdasfgvbarg asfvaifhmwq8ecngwa8e gtvw8efhaweuftgewaygnerhyfgwe78frhmrgcruHR iyrygmHFYUAWGFHAWF HGAEGYAERURHGMAEROUIGHAEURIGFHAERWUGFHAERUGHAEYUGiabgseweuhBFAWUYFGWeuyfweyFHWEYFVAWEGFAEUGVWYEVGFWgwgyybaghjvsuygbgvyrdasfgvbarg asfvaifhmwq8ecngwa8e gtvw8efhaweuftgewaygnerhyfgwe78frhmrgcruHR iyrygmHFYUAWGFHAWF HGAEGYAERURHGMAEROUIGHAEURIGFHAERWUGFHAERUGHAEYUGiabgseweuhBFAWUYFGWeuyfweyFHWEYFVAWEGFAEUGVWYEVGFWgwgyybaghjvsuygbgvyrdasfgvbarg asfvaifhmwq8ecngwa8e gtvw8efhaweuftgewaygnerhyfgwe78frhmrgcruHR iyrygmHFYUAWGFHAWF HGAEGYAERURHGMAEROUIGHAEURIGFHAERWUGFHAERUGHAEYUGiabgseweuhBFAWUYFGWeuyfweyFHWEYFVAWEGFAEUGVWYEVGFWgwgyybaghjvsuygbgvyrdasfgvbarg asfvaifhmwq8ecngwa8e gtvw8efhaweuftgewaygnerhyfgwe78frhmrgcruHR iyrygmHFYUAWGFHAWF HGAEGYAERURHGMAEROUIGHAEURIGFHAERWUGFHAERUGHAEYUGiabgseweuhBFAWUYFGWeuyfweyFHWEYFVAWEGFAEUGVWYEVGFWgwgyybaghjvsuygbgvyrdasfgvbarg asfvaifhmwq8ecngwa8e gtvw8efhaweuftgewaygnerhyfgwe78frhmrgcruHR iyrygmHFYUAWGFHAWF HGAEGYAERURHGMAEROUIGHAEURIGFHAERWUGFHAERUGHAEYUGiabgseweuhBFAWUYFGWeuyfweyFHWEYFVAWEGFAEUGVWYEVGFWgwgyybaghjvsuygbgvyrdasfgvbarg asfvaifhmwq8ecngwa8e gtvw8efhaweuftgewaygnerhyfgwe78frhmrgcruHR iyrygmHFYUAWGFHAWF HGAEGYAERURHGMAEROUIGHAEURIGFHAERWUGFHAERUGHAEYUGiabgseweuhBFAWUYFGWeuyfweyFHWEYFVAWEGFAEUGVWYEVGFWgwgyybaghjvsuygbgvyrdasfgvbarg asfvaifhmwq8ecngwa8e gtvw8efhaweuftgewaygnerhyfgwe78frhmrgcruHR iyrygmHFYUAWGFHAWF HGAEGYAERURHGMAEROUIGHAEURIGFHAERWUGFHAERUGHAEYUGiabgseweuhBFAWUYFGWeuyfweyFHWEYFVAWEGFAEUGVWYEVGFWgwgyybaghjvsuygbgvyrdasfgvbarg asfvaifhmwq8ecngwa8e gtvw8efhaweuftgewaygnerhyfgwe78frhmrgcruHR iyrygmHFYUAWGFHAWF HGAEGYAERURHGMAEROUIGHAEURIGFHAERWUGFHAERUGHAEYUGiabgseweuhBFAWUYFGWeuyfweyFHWEYFVAWEGFAEUGVWYEVGFWgwgyybaghjvsuygbgvyrdasfgvbarg asfvaifhmwq8ecngwa8e gtvw8efhaweuftgewaygnerhyfgwe78frhmrgcruHR iyrygmHFYUAWGFHAWF HGAEGYAERURHGMAEROUIGHAEURIGFHAERWUGFHAERUGHAEYUGiabgseweuhBFAWUYFGWeuyfweyFHWEYFVAWEGFAEUGVWYEVGFWgwgyybaghjvsuygbgvyrdasfgvbarg asfvaifhmwq8ecngwa8e gtvw8efhaweuftgewaygnerhyfgwe78frhmrgcruHR iyrygmHFYUAWGFHAWF HGAEGYAERURHGMAEROUIGHAEURIGFHAERWUGFHAERUGHAEYUGiabgseweuhBFAWUYFGWeuyfweyFHWEYFVAWEGFAEUGVWYEVGFWgwgyybaghjvsuygbgvyrdasfgvbarg asfvaifhmwq8ecngwa8e gtvw8efhaweuftgewaygnerhyfgwe78frhmrgcruHR iyrygmHFYUAWGFHAWF HGAEGYAERURHGMAEROUIGHAEURIGFHAERWUGFHAERUGHAEYUGiabgseweuhBFAWUYFGWeuyfweyFHWEYFVAWEGFAEUGVWYEVGFWgwgyybaghjvsuygbgvyrdasfgvbarg asfvaifhmwq8ecngwa8e gtvw8efhaweuftgewaygnerhyfgwe78frhmrgcruHR iyrygmHFYUAWGFHAWF HGAEGYAERURHGMAEROUIGHAEURIGFHAERWUGFHAERUGHAEYUGiabgseweuhBFAWUYFGWeuyfweyFHWEYFVAWEGFAEUGVWYEVGFWgwgyybaghjvsuygbgvyrdasfgvbarg asfvaifhmwq8ecngwa8e gtvw8efhaweuftgewaygnerhyfgwe78frhmrgcruHR iyrygmHFYUAWGFHAWF HGAEGYAERURHGMAEROUIGHAEURIGFHAERWUGFHAERUGHAEYUGiabgseweuhBFAWUYFGWeuyfweyFHWEYFVAWEGFAEUGVWYEVGFWgwgyybaghjvsuygbgvyrdasfgvbarg asfvaifhmwq8ecngwa8e gtvw8efhaweuftgewaygnerhyfgwe78frhmrgcruHR iyrygmHFYUAWGFHAWF HGAEGYAERURHGMAEROUIGHAEURIGFHAERWUGFHAERUGHAEYUGiabgseweuhBFAWUYFGWeuyfweyFHWEYFVAWEGFAEUGVWYEVGFWgwgyybaghjvsuygbgvyrdasfgvbarg asfvaifhmwq8ecngwa8e gtvw8efhaweuftgewaygnerhyfgwe78frhmrgcruHR iyrygmHFYUAWGFHAWF HGAEGYAERURHGMAEROUIGHAEURIGFHAERWUGFHAERUGHAEYUGiabgseweuhBFAWUYFGWeuyfweyFHWEYFVAWEGFAEUGVWYEVGFWgwgyybaghjvsuygbgvyrdasfgvbarg asfvaifhmwq8ecngwa8e gtvw8efhaweuftgewaygnerhyfgwe78frhmrgcruHR iyrygmHFYUAWGFHAWF HGAEGYAERURHGMAEROUIGHAEURIGFHAERWUGFHAERUGHAEYUG")
            Text("collaboration omg")
            Text("JEW")
            Text("JEW")
            Text("JEW")
            Text("JEW")
            Text("JEW")
            Text("JEW")
            Text("JEW")
            Text("JEW")
            Text("JEW")
            Text("JEW")
            Text("JEW")
            Text("CHINA")
            
        }
        .padding()
    }
}

#Preview {
    ContentView()
}
